# Generated by Django 3.1 on 2023-10-19 10:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0018_auto_20231019_1338'),
    ]

    operations = [
        migrations.AlterField(
            model_name='contractor',
            name='category',
            field=models.CharField(choices=[('individual', 'Физическое лицо'), ('entity', 'Юридическое лицо'), ('INN', 'ИНН')], max_length=20, verbose_name='Категория'),
        ),
    ]
