# Generated by Django 3.1 on 2023-11-01 06:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0021_contractor_inn'),
    ]

    operations = [
        migrations.AlterField(
            model_name='contractor',
            name='inn',
            field=models.CharField(max_length=12, unique=True),
        ),
    ]
