# Generated by Django 3.1 on 2023-11-01 08:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0024_auto_20231101_0941'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='inventory_number',
            field=models.CharField(default='', max_length=100, verbose_name='инв.№'),
        ),
    ]
