# Generated by Django 3.1 on 2023-11-02 08:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0025_product_inventory_number'),
    ]

    operations = [
        migrations.AddField(
            model_name='contractor',
            name='address',
            field=models.TextField(default='  ', verbose_name='Юридический адрес, контактный телефон'),
        ),
        migrations.AlterField(
            model_name='contractor',
            name='category',
            field=models.CharField(choices=[('individual', 'Физическое лицо'), ('entity', 'Юридическое лицо'), ('IOGV', 'ИОГВ')], max_length=20, verbose_name='Категория Контрагента'),
        ),
    ]
