# Generated by Django 3.1 on 2023-11-02 08:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0026_auto_20231102_1115'),
    ]

    operations = [
        migrations.AlterField(
            model_name='contractor',
            name='category',
            field=models.CharField(choices=[('individual', 'Физическое лицо'), ('entity', 'Юридическое лицо'), ('IOGV', 'орган государственной власти')], max_length=20, verbose_name='Категория Контрагента'),
        ),
    ]
